### ISSUE TITLE
Enhancement: Support for Windows

### ISSUE THREAD

**Issue by mrsauravsahu** [mrsauravsahu/vscode-manager#4]

**Comment by DAmNRelentless** [comment]
Any ETA when you have time to work on this again? The extension looks very promising.

**Comment by saurav-sahu-mck** [comment]
Thanks @DAmNRelentless! I was mainly working on Linux but I can get on Windows support if you'd like :)

**Comment by mrsauravsahu** [comment]
Thanks @DAmNRelentless! I was mainly working on Linux, but I can get on Windows Support if you'd like :) 

Appreciate contributions as well 😄

**Comment by DAmNRelentless** [comment]
That would be awesome. I sadly rely on Windows most of the time.
My only Linux environment is WSL2 which I am running with Ubuntu but that's another story.

I may take a look at your code when I got some time.

**Comment by mrsauravsahu** [comment]
@DAmNRelentless do let me know how it works and provide feedback :)

**Comment by DAmNRelentless** [comment]
Installed the extension again and I am trying to create a new profile and I get the following error:
```
'mrsauravsahu.vscode-manager' failed: ENOENT: no such file or directory, mkdir 'C:\Users\Relentless\.config\vscode-manager'.
```
Could be a permission error though.

I now created the folder manually although I find it a bit odd to create a new folder within the user profile folder and not within 
 the already existing .vscode folder.
After creating it manually, it seems to work fine. When I launch my new profile, it looks like a completely new VSCode instance. I copied my settings over and installed some extensions. That worked fine as well.

I thought it would be a little different though. I know that's probably not the purpose of this extension but I am more looking for something that let's me define a profile for each project folder like inside the `.vscode/settings.json` which would be automatically activated when opening the folder.
That would be nice to switch extensions automatically e.g. when working with many projects in different languages.

I probably find a handy way of using your extension anyways so thank you for your work on the Windows version!

**Comment by mrsauravsahu** [comment]
Hey @DAmNRelentless thanks for trying out Custom Profiles! I did realise the permission issue would come up - I'd created an issue for it before #8.

Yep, let's see if we can ask the user to add permission through VSCode or else we'll change the location of the profiles to inside `~/.vscode`

Yep, the file for each folder is half-way there - checkout this section of the readme. You can create a `profile.json` file - https://github.com/mrsauravsahu/vscode-manager#sharing-a-custom-profile-between-your-team

Launching through this file just opens the custom profiles. But you're right, opening the same folder is what I'd want as well.

**Comment by DAmNRelentless** [comment]
Sounds pretty nice, thanks for the response!

On your todo list I saw that there is also profile duplication left.
Do you intend to do something like being able to select which extensions you want for your new profile?

Like in my situation where I have no profile yet, creating a new one is not very convenient since it just gives me like a separate VSCode install where I have to set up everything myself.
Copying the settings isn't very hard but could be made more convenient by a little popup when creating the new profile if you want to copy your current settings over.
Installing each extension again on the other hand is a bit tedious. A checkbox list would be nice which extensions you want to install on your new profile. Or a list in the config which extensions should be installed automatically for each new profile.

I am curious about the future of this extension. Keep it going, good work! :)

**Comment by mrsauravsahu** [comment]
Hey @DAmNRelentless this is available now! Hope this works well. Do let me know how it goes! 😁
